apiVersion: v2
name: crud-app-chart
description: A Helm chart for Kubernetes

type: application

version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami