server:
  port: 8000

management:
  health:
    probes:
      enabled: false
  endpoint:
    health:
      enabled: true
      show-details: never
      status:
        order: FATAL,DOWN,OUT_OF_SERVICE,UNKNOWN,OK,UP
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: '*'