apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud-app-chart.fullname" . }}
  labels:
    {{- include "crud-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateType }}
  selector:
    matchLabels:
      {{- include "crud-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "crud-app-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: web
              containerPort: 8000
              protocol: TCP              
          env:
            - name: pg.password
              valueFrom:
                secretKeyRef:
                  name: crud-secret
                  key: PG_PASSWORD
            - name: pg.user
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: PG_USER
            - name: pg.port
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: PG_PORT
            - name: pg.db
              valueFrom:
                configMapKeyRef:
                  name: crud-config
                  key: PG_DB                  
          livenessProbe:
              httpGet:
                port: web
                path: /api/v1/health
              initialDelaySeconds: 60
              periodSeconds: 15
          readinessProbe:
              httpGet:
                port: web
                path: /api/v1/health
              initialDelaySeconds: 5
              periodSeconds: 3                  