{
 "title": "CRUD APP DASHBOARD",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Pods metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods RAM Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container=\"crud-app-chart\"}) by (pod)",
     "legendFormat": "   {{` {{  pod  }} `}}   "
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container=\"crud-app-chart\"}[1m])) by (pod)",
     "legendFormat": "   {{` {{  pod  }} `}}   "
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "App Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "0.5:    {{` {{  method  }} `}}       {{` {{  uri  }} `}}   "
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n)",
     "legendFormat": "0.95:    {{` {{  method  }} `}}       {{` {{  uri  }} `}}   "
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n) ",
     "legendFormat": "0.99:    {{` {{  method  }} `}}       {{` {{  uri  }} `}}   "
    },
    {
     "expr": "histogram_quantile(1,\r\n  sum by (le, uri, method)\r\n  (rate(http_server_requests_seconds_bucket[1m]))\r\n) ",
     "legendFormat": "Max:    {{` {{  method  }} `}}       {{` {{  uri  }} `}}   "
    }
   ]
  },
  {
   "title": "App RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, method) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "   {{` {{  method  }} `}}       {{` {{  uri  }} `}}   "
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.5:    {{` {{  method  }} `}}       {{` {{  path  }} `}}   "
    },
    {
     "expr": "histogram_quantile(0.9, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.9:    {{` {{  method  }} `}}       {{` {{  path  }} `}}   "
    },
    {
     "expr": "histogram_quantile(0.95, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "0.95:    {{` {{  method  }} `}}       {{` {{  path  }} `}}   "
    },
    {
     "expr": "histogram_quantile(1, \n  sum by (le, path, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])) \n)",
     "legendFormat": "Max:    {{` {{  method  }} `}}       {{` {{  path  }} `}}   "
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path, method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "   {{` {{  path  }} `}}       {{` {{  method  }} `}}   "
    }
   ]
  },
  {
   "title": "App Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"[5].+\"}[1m]))/sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[5].+\"}[1m])) / sum(rate(nginx_ingress_controller_requests[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Error Rate count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status)\r\n(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DB Open File Description",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"pg-exporter:80\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=~\"otus_crud_app\"} !=0",
     "legendFormat": "   {{` {{  state  }} `}}   "
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_conflicts{datname=\"otus_crud_app\"}",
     "legendFormat": "   {{` {{  datname  }} `}}    conflicts"
    }
   ]
  },
  {
   "title": "DB Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"otus_crud_app\"}",
     "legendFormat": "   {{` {{  datname  }} `}}    commits"
    }
   ]
  },
  {
   "title": "DB Select data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"otus_crud_app\"} != 0",
     "legendFormat": "   {{` {{  datname  }} `}}   "
    }
   ]
  },
  {
   "title": "DB Delete data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{datname=\"otus_crud_app\"} != 0",
     "legendFormat": "   {{` {{  datname  }} `}}   "
    }
   ]
  },
  {
   "title": "DB Update data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{datname=\"otus_crud_app\"} != 0",
     "legendFormat": "   {{` {{  datname  }} `}}   "
    }
   ]
  },
  {
   "title": "DB Insert data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"otus_crud_app\"} != 0",
     "legendFormat": "   {{` {{  datname  }} `}}   "
    }
   ]
  }
 ]
}