apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  PG_DB: {{ .Values.postgresql.postgresqlDatabase | quote }}
  PG_PORT: {{ .Values.postgresql.service.port | quote }}  
  PG_USER: {{ .Values.postgresql.postgresqlUsername | quote }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  PG_PASSWORD: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}  
  REDIS_PASSWORD: {{ .Values.redis.password  | b64enc | quote }}  